### ISSUE TITLE
Where's the love?

### ISSUE THREAD

**Issue by ecorm** [ahupowerdns/luawrapper#15]
There are currently 8 pending pull requests sitting here since last year. Is this library still being maintained?

Is there another fork of this library being actively maintained? Can someone recommend an alternative library that supports optional and variant variables?

**Comment by Habbie** [comment]
@ecorm I am picking up maintainership of this now

**Comment by Habbie** [comment]
If you want to help me get this into shape again, I could use reviews on any open PRs you feel qualified to judge!
