### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Kayomn** [ahupowerdns/luawrapper#39]
This code appears to cause an unhandled exception at runtime from within the library itself:

```cpp
LuaContext lua;

lua.writeVariable("out",[]() {
	std::cout << "Hello world" << std::endl;
});
lua.executeCode(std::ifstream{"scripts/test.lua"});
```

The exception in particular occurs when trying to execute any kind of code, be it a string, a file, etc.

Visual Studios debugger states it occurs within the definition of:
`callRaw(lua_State*,PushedObject,const int);`

![evidence](https://user-images.githubusercontent.com/15730577/32721713-5154d686-c85f-11e7-8397-e74a475c1719.png)

Not sure if this same error occurs in other compilers as I have not yet had time to check.

**Comment by meizhaohui** [comment]
if you change the test.lua encode without BOM , It will run OK.

**Comment by Habbie** [comment]
This ticket does not have enough detail to act on. Closing.
